#!/usr/bin/env python3
"""Train full-scale next-stop preference models.

This script trains binary preference models on pairwise samples generated by
09_create_full_pairwise_samples.py. Each row represents a current stop i and a
candidate next stop j. The target label is 1 when j is the actual next stop and
0 when j is a sampled negative candidate from the same route context.

The primary model-selection metric is validation sampled_top1_accuracy: within
each route_id + position decision context, the best model should rank the true
next stop highest among the sampled candidates.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
import warnings
from datetime import datetime, timezone
from importlib.util import find_spec
from pathlib import Path
from typing import Any, Sequence


VALID_SPLITS = ("train", "validation", "test")
VALID_MODELS = (
    "logistic_regression",
    "random_forest",
    "xgboost",
    "lightgbm",
    "catboost",
)
MODEL_CHOICES = (*VALID_MODELS, "all")

DEFAULT_CONFIG_PATH = Path("config/config_final.yaml")
DEFAULT_INPUT_DIR = Path(
    "/content/drive/MyDrive/dissertation/amazon_last_mile/"
    "final_experiment_outputs/pairwise_samples_full"
)
DEFAULT_OUTPUT_DIR = Path(
    "/content/drive/MyDrive/dissertation/amazon_last_mile/"
    "final_experiment_outputs/model_outputs_full"
)

TARGET_COLUMN = "label"
CONTEXT_COLUMNS = ["route_id", "position"]
PREDICTION_ID_COLUMNS = [
    "route_id",
    "position",
    "current_stop",
    "candidate_stop",
    "actual_next_stop",
    "label",
]

DEFAULT_FEATURE_COLUMNS = [
    "travel_time_ij",
    "same_zone",
    "zone_changed",
    "zone_missing_in_pair",
    "number_of_stops",
    "route_progress",
    "remaining_stop_count",
    "current_is_station",
    "current_is_dropoff",
    "candidate_is_station",
    "candidate_is_dropoff",
    "candidate_package_count",
    "candidate_total_planned_service_time",
    "candidate_has_time_window",
    "candidate_time_window_package_count",
    "candidate_total_package_volume_cm3",
    "candidate_delivered_count",
    "candidate_attempted_count",
    "candidate_rejected_count",
    "candidate_unknown_status_count",
]

EXCLUDED_FEATURE_COLUMNS = {
    "route_id",
    "split",
    "position",
    "current_stop",
    "candidate_stop",
    "actual_next_stop",
    "label",
    "route_score",
    "current_zone",
    "candidate_zone",
    "current_type",
    "candidate_type",
    "negative_sampling_seed",
    "negative_sample_rank",
    "travel_time_source",
    "generation_timestamp",
}

FEATURE_IMPORTANCE_COLUMNS = [
    "model_name",
    "feature",
    "importance",
    "signed_importance",
    "importance_type",
]

MODEL_SKIPPED_COLUMNS = ["model_name", "reason"]
MODEL_TRAINED_COLUMNS = ["model_name", "model_path"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train and compare full-scale preference learning models from "
            "pairwise next-stop samples."
        )
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help=(
            "Path to config YAML. Used for default input/output directories "
            "and seed. Default: config/config_final.yaml."
        ),
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=None,
        help=(
            "Directory containing train/validation/test pairwise samples. "
            "Defaults to outputs.pairwise_full_dir from config."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory for trained models and metrics. Defaults to "
            "outputs.model_full_dir from config."
        ),
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=["all"],
        choices=MODEL_CHOICES,
        help=(
            "Models to train. Use 'all' for every supported model. "
            "Default: all."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help=(
            "Random seed. Defaults to pairwise.default_seed from config if "
            "available, otherwise 42."
        ),
    )
    parser.add_argument(
        "--input-format",
        choices=("auto", "parquet", "csv"),
        default="auto",
        help="Input file format. Auto prefers parquet, then CSV. Default: auto.",
    )
    parser.add_argument(
        "--max-train-contexts",
        type=int,
        default=None,
        help="Optional maximum number of complete train decision contexts.",
    )
    parser.add_argument(
        "--max-validation-contexts",
        type=int,
        default=None,
        help="Optional maximum number of complete validation decision contexts.",
    )
    parser.add_argument(
        "--max-test-contexts",
        type=int,
        default=None,
        help="Optional maximum number of complete test decision contexts.",
    )
    parser.add_argument(
        "--max-train-rows",
        type=int,
        default=None,
        help=(
            "Optional maximum number of train rows. Used only when "
            "--max-train-contexts is not provided. This may break decision "
            "contexts and is not recommended for top-k metrics."
        ),
    )
    parser.add_argument(
        "--class-weight",
        choices=("none", "balanced"),
        default="balanced",
        help="Class weighting strategy for supported models. Default: balanced.",
    )
    parser.add_argument(
        "--save-predictions",
        action="store_true",
        help="Save validation/test prediction CSV files for every trained model.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow overwriting files in an existing non-empty output directory.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print additional progress and data diagnostics.",
    )
    return parser.parse_args()


def load_config(path: Path) -> dict[str, Any]:
    """Load YAML config. Missing config returns an empty mapping with a warning."""

    if not path.exists():
        warnings.warn(f"Config file not found: {path}. Falling back to defaults.")
        return {}

    try:
        import yaml
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise SystemExit("Please install pyyaml: pip install pyyaml") from exc

    with path.open("r", encoding="utf-8") as file_obj:
        data = yaml.safe_load(file_obj) or {}

    if not isinstance(data, dict):
        raise ValueError(f"Config file must contain a YAML mapping: {path}")

    return data


def resolve_path(path: Any) -> Path:
    """Resolve local paths while preserving absolute Colab-style paths."""

    if path is None:
        raise ValueError("Cannot resolve a null path.")

    if isinstance(path, dict) and "candidates" in path:
        candidates = [resolve_path(candidate) for candidate in path["candidates"]]
        for candidate in candidates:
            if candidate.exists():
                return candidate
        return candidates[0]

    if isinstance(path, (list, tuple)):
        candidates = [resolve_path(candidate) for candidate in path if candidate is not None]
        for candidate in candidates:
            if candidate.exists():
                return candidate
        if candidates:
            return candidates[0]
        raise ValueError("Cannot resolve an empty path candidate list.")

    resolved = Path(str(path)).expanduser()
    if resolved.is_absolute():
        return resolved
    return resolved.resolve()


def resolve_runtime_settings(args: argparse.Namespace, config: dict[str, Any]) -> dict[str, Any]:
    outputs = config.get("outputs", {}) if isinstance(config.get("outputs", {}), dict) else {}
    pairwise = config.get("pairwise", {}) if isinstance(config.get("pairwise", {}), dict) else {}

    input_dir = resolve_path(args.input_dir or outputs.get("pairwise_full_dir", DEFAULT_INPUT_DIR))
    output_dir = resolve_path(args.output_dir or outputs.get("model_full_dir", DEFAULT_OUTPUT_DIR))
    seed = args.seed if args.seed is not None else int(pairwise.get("default_seed", 42))

    return {
        "input_dir": input_dir,
        "output_dir": output_dir,
        "seed": seed,
    }


def requested_models_from_args(args: argparse.Namespace, config: dict[str, Any]) -> list[str]:
    if "all" not in args.models:
        return list(dict.fromkeys(args.models))

    model_cfg = config.get("model", {}) if isinstance(config.get("model", {}), dict) else {}
    configured = model_cfg.get("models", VALID_MODELS)
    if not isinstance(configured, list):
        configured = list(VALID_MODELS)

    models = []
    for model_name in configured:
        if model_name in VALID_MODELS:
            models.append(model_name)
        else:
            warnings.warn(f"Ignoring unsupported model from config: {model_name}")

    return list(dict.fromkeys(models or list(VALID_MODELS)))


def find_pairwise_file(input_dir: Path, split: str, input_format: str) -> Path:
    """Find one split file, preferring parquet when input_format is auto."""

    if split not in VALID_SPLITS:
        raise ValueError(f"Unsupported split: {split}")

    parquet_path = input_dir / f"{split}_pairwise_samples.parquet"
    csv_path = input_dir / f"{split}_pairwise_samples.csv"

    if input_format == "auto":
        if parquet_path.exists():
            return parquet_path
        if csv_path.exists():
            return csv_path
        raise FileNotFoundError(
            f"Missing {split} pairwise samples. Checked: {parquet_path}, {csv_path}"
        )

    if input_format == "parquet":
        if parquet_path.exists():
            return parquet_path
        raise FileNotFoundError(f"Missing requested parquet input: {parquet_path}")

    if input_format == "csv":
        if csv_path.exists():
            return csv_path
        raise FileNotFoundError(f"Missing requested CSV input: {csv_path}")

    raise ValueError(f"Unsupported input format: {input_format}")


def parquet_engine_available() -> bool:
    return find_spec("pyarrow") is not None or find_spec("fastparquet") is not None


def list_parquet_columns(path: Path) -> list[str]:
    if find_spec("pyarrow") is not None:
        import pyarrow.parquet as pq

        return list(pq.read_schema(path).names)

    if find_spec("fastparquet") is not None:
        import fastparquet

        return list(fastparquet.ParquetFile(path).columns)

    raise RuntimeError(
        "Parquet input requires pyarrow or fastparquet. "
        "Use --input-format csv or install a parquet engine."
    )


def list_input_columns(path: Path) -> list[str]:
    import pandas as pd

    suffix = path.suffix.lower()
    if suffix == ".parquet":
        return list_parquet_columns(path)
    if suffix == ".csv":
        return list(pd.read_csv(path, nrows=0).columns)
    raise ValueError(f"Unsupported input file extension: {path}")


def read_pairwise_split(
    input_dir: Path,
    split: str,
    input_format: str,
    columns: Sequence[str],
) -> Any:
    """Read one pairwise split using only requested columns that exist."""

    import pandas as pd

    path = find_pairwise_file(input_dir, split, input_format)
    suffix = path.suffix.lower()
    requested = list(dict.fromkeys(columns))
    available = list_input_columns(path)
    available_set = set(available)
    usecols = [column for column in requested if column in available_set]
    missing = [column for column in requested if column not in available_set]

    if missing:
        warnings.warn(f"{split}: missing requested columns: {missing}")
    if not usecols:
        raise ValueError(f"{split}: no requested columns are available in {path}")

    print(f"Reading {split}: {path}")
    print(f"{split}: reading {len(usecols)} of {len(available)} available columns")

    if suffix == ".parquet":
        if not parquet_engine_available():
            raise RuntimeError(
                "Parquet input requires pyarrow or fastparquet. "
                "Use --input-format csv or install a parquet engine."
            )
        return pd.read_parquet(path, columns=usecols)

    if suffix == ".csv":
        return pd.read_csv(path, usecols=usecols)

    raise ValueError(f"Unsupported input file extension: {path}")


def sample_decision_contexts(df: Any, max_contexts: int | None, seed: int) -> Any:
    """Sample complete route_id + position groups."""

    if max_contexts is None or max_contexts <= 0:
        return df

    missing = [column for column in CONTEXT_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(f"Cannot sample decision contexts; missing columns: {missing}")

    contexts = df.loc[:, CONTEXT_COLUMNS].drop_duplicates()
    if len(contexts) <= max_contexts:
        return df

    sampled_contexts = contexts.sample(n=max_contexts, random_state=seed)
    sampled = df.merge(sampled_contexts, on=CONTEXT_COLUMNS, how="inner")
    sampled = sampled.reset_index(drop=True)

    print(
        f"Sampled {len(sampled_contexts):,} complete decision contexts; "
        f"rows kept: {len(sampled):,} of {len(df):,}"
    )
    return sampled


def sample_rows(df: Any, max_rows: int | None, seed: int, split: str) -> Any:
    if max_rows is None or max_rows <= 0 or len(df) <= max_rows:
        return df

    warnings.warn(
        "Row sampling may break decision contexts and should not be used for top-k metrics."
    )
    sampled = df.sample(n=max_rows, random_state=seed).reset_index(drop=True)
    print(f"{split}: sampled {len(sampled):,} rows from {len(df):,} rows")
    return sampled


def label_counts(df: Any) -> dict[str, int]:
    labels = df[TARGET_COLUMN].value_counts(dropna=False).sort_index()
    return {str(label): int(count) for label, count in labels.items()}


def validate_pairwise_data(df: Any, split: str) -> dict[str, Any]:
    """Validate required columns and report decision-context quality."""

    missing_required = [
        column for column in [*CONTEXT_COLUMNS, TARGET_COLUMN] if column not in df.columns
    ]
    if missing_required:
        raise ValueError(f"{split}: missing required columns: {missing_required}")

    if df.empty:
        raise ValueError(f"{split}: input data is empty.")

    labels = df[TARGET_COLUMN]
    numeric_labels = labels.astype("int64")
    observed = set(numeric_labels.dropna().unique().tolist())
    if not observed.issubset({0, 1}):
        raise ValueError(f"{split}: labels must be 0/1. Observed: {sorted(observed)}")

    context_positive_counts = (
        numeric_labels.eq(1)
        .groupby([df["route_id"], df["position"]], dropna=False)
        .sum()
    )
    contexts = int(len(context_positive_counts))
    no_positive = int((context_positive_counts == 0).sum())
    multiple_positive = int((context_positive_counts > 1).sum())
    not_exactly_one = no_positive + multiple_positive

    if not_exactly_one:
        warnings.warn(
            f"{split}: {not_exactly_one:,} decision contexts do not have exactly "
            "one positive sample."
        )

    summary = {
        "split": split,
        "rows": int(len(df)),
        "decision_contexts": contexts,
        "positive_rows": int((numeric_labels == 1).sum()),
        "negative_rows": int((numeric_labels == 0).sum()),
        "contexts_no_positive": no_positive,
        "contexts_multiple_positive": multiple_positive,
        "contexts_not_exactly_one_positive": not_exactly_one,
    }

    print(
        f"{split}: rows={summary['rows']:,}, contexts={contexts:,}, "
        f"labels={label_counts(df)}"
    )
    return summary


def get_feature_columns(df: Any) -> list[str]:
    """Return default numeric features available in the dataframe."""

    available = []
    missing = []
    excluded_present = sorted(set(df.columns) & EXCLUDED_FEATURE_COLUMNS)

    for column in DEFAULT_FEATURE_COLUMNS:
        if column in df.columns and column not in EXCLUDED_FEATURE_COLUMNS:
            available.append(column)
        else:
            missing.append(column)

    if missing:
        warnings.warn(f"Missing default feature columns: {missing}")
    if "route_score" in excluded_present:
        print("Excluding route_score from features to avoid leakage.")

    if not available:
        raise ValueError("No usable feature columns remain.")

    return available


def prepare_xy(df: Any, feature_columns: Sequence[str]) -> tuple[Any, Any]:
    """Convert feature columns to numeric X and labels to integer y."""

    import pandas as pd

    missing = [column for column in feature_columns if column not in df.columns]
    if missing:
        raise ValueError(f"Missing feature columns during prepare_xy: {missing}")

    features = df.loc[:, list(feature_columns)].copy()
    for column in feature_columns:
        features[column] = pd.to_numeric(features[column], errors="coerce")
    features = features.astype("float32")

    labels = pd.to_numeric(df[TARGET_COLUMN], errors="coerce")
    if labels.isna().any():
        raise ValueError("Labels contain non-numeric values after conversion.")
    labels = labels.astype("int64")

    return features, labels


def train_model(
    model_name: str,
    X_train: Any,
    y_train: Any,
    seed: int,
    class_weight: str,
) -> Any:
    """Build and fit one requested model."""

    balanced = class_weight == "balanced"

    try:
        from sklearn.impute import SimpleImputer
        from sklearn.pipeline import Pipeline
    except ImportError as exc:
        raise ImportError("scikit-learn is required for model pipelines.") from exc

    if model_name == "logistic_regression":
        from sklearn.linear_model import LogisticRegression
        from sklearn.preprocessing import StandardScaler

        estimator = LogisticRegression(
            max_iter=1000,
            solver="lbfgs",
            class_weight="balanced" if balanced else None,
            random_state=seed,
        )
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", estimator),
            ]
        )
    elif model_name == "random_forest":
        from sklearn.ensemble import RandomForestClassifier

        estimator = RandomForestClassifier(
            n_estimators=200,
            max_depth=None,
            min_samples_leaf=2,
            n_jobs=-1,
            class_weight="balanced_subsample" if balanced else None,
            random_state=seed,
        )
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("model", estimator),
            ]
        )
    elif model_name == "xgboost":
        if find_spec("xgboost") is None:
            raise ImportError("xgboost is not installed.")
        from xgboost import XGBClassifier

        estimator = XGBClassifier(
            objective="binary:logistic",
            eval_metric="logloss",
            n_estimators=500,
            max_depth=6,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            n_jobs=-1,
            random_state=seed,
        )
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("model", estimator),
            ]
        )
    elif model_name == "lightgbm":
        if find_spec("lightgbm") is None:
            raise ImportError("lightgbm is not installed.")
        from lightgbm import LGBMClassifier

        estimator = LGBMClassifier(
            n_estimators=500,
            learning_rate=0.05,
            num_leaves=63,
            subsample=0.8,
            colsample_bytree=0.8,
            class_weight="balanced" if balanced else None,
            random_state=seed,
            n_jobs=-1,
            verbose=-1,
        )
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("model", estimator),
            ]
        )
    elif model_name == "catboost":
        if find_spec("catboost") is None:
            raise ImportError("catboost is not installed.")
        from catboost import CatBoostClassifier

        kwargs = {
            "iterations": 600,
            "depth": 8,
            "learning_rate": 0.05,
            "loss_function": "Logloss",
            "eval_metric": "AUC",
            "random_seed": seed,
            "verbose": False,
            "allow_writing_files": False,
        }
        if balanced:
            kwargs["auto_class_weights"] = "Balanced"
        estimator = CatBoostClassifier(**kwargs)
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("model", estimator),
            ]
        )
    else:
        raise ValueError(f"Unsupported model: {model_name}")

    model.fit(X_train, y_train)
    return model


def predict_proba_safely(model: Any, X: Any) -> Any:
    """Return a clipped probability for the positive class."""

    import numpy as np

    if hasattr(model, "predict_proba"):
        probabilities = np.asarray(model.predict_proba(X), dtype=float)
        if probabilities.ndim == 2:
            classes = getattr(model, "classes_", None)
            if classes is not None and 1 in list(classes):
                positive_index = list(classes).index(1)
            else:
                positive_index = min(1, probabilities.shape[1] - 1)
            y_prob = probabilities[:, positive_index]
        else:
            y_prob = probabilities.reshape(-1)
    elif hasattr(model, "decision_function"):
        scores = np.asarray(model.decision_function(X), dtype=float).reshape(-1)
        scores = np.clip(scores, -700, 700)
        y_prob = 1.0 / (1.0 + np.exp(-scores))
    else:
        y_prob = np.asarray(model.predict(X), dtype=float).reshape(-1)

    return np.clip(y_prob, 1e-15, 1.0 - 1e-15)


def compute_binary_metrics(y_true: Any, y_prob: Any) -> dict[str, float]:
    """Compute binary metrics safely."""

    import numpy as np
    from sklearn.metrics import (
        accuracy_score,
        average_precision_score,
        f1_score,
        log_loss,
        precision_score,
        recall_score,
        roc_auc_score,
    )

    y_true = np.asarray(y_true, dtype=int)
    y_prob = np.asarray(y_prob, dtype=float)
    y_pred = (y_prob >= 0.5).astype(int)

    def safe(name: str, func: Any) -> float:
        try:
            return float(func())
        except Exception as exc:
            warnings.warn(f"Could not compute {name}: {exc}")
            return float("nan")

    return {
        "accuracy": safe("accuracy", lambda: accuracy_score(y_true, y_pred)),
        "precision": safe(
            "precision", lambda: precision_score(y_true, y_pred, zero_division=0)
        ),
        "recall": safe("recall", lambda: recall_score(y_true, y_pred, zero_division=0)),
        "f1": safe("f1", lambda: f1_score(y_true, y_pred, zero_division=0)),
        "roc_auc": safe("roc_auc", lambda: roc_auc_score(y_true, y_prob)),
        "average_precision": safe(
            "average_precision", lambda: average_precision_score(y_true, y_prob)
        ),
        "log_loss": safe("log_loss", lambda: log_loss(y_true, y_prob, labels=[0, 1])),
    }


def compute_sampled_topk_metrics(df: Any, y_prob: Any) -> dict[str, Any]:
    """Compute sampled top-k accuracy by route_id + position context."""

    import numpy as np

    missing = [column for column in [*CONTEXT_COLUMNS, TARGET_COLUMN] if column not in df.columns]
    if missing:
        warnings.warn(f"Cannot compute top-k metrics; missing columns: {missing}")
        return {
            "sampled_top1_accuracy": float("nan"),
            "sampled_top3_accuracy": float("nan"),
            "sampled_top5_accuracy": float("nan"),
            "evaluated_contexts": 0,
            "skipped_contexts_no_positive": 0,
            "contexts_multiple_positive": 0,
        }

    temp = df.loc[:, [*CONTEXT_COLUMNS, TARGET_COLUMN]].copy()
    temp[TARGET_COLUMN] = temp[TARGET_COLUMN].astype("int64")
    temp["predicted_probability"] = np.asarray(y_prob, dtype=float)

    positive_counts = temp.groupby(CONTEXT_COLUMNS, dropna=False)[TARGET_COLUMN].sum()
    skipped_no_positive = int((positive_counts == 0).sum())
    multiple_positive = int((positive_counts > 1).sum())

    ranked = temp.sort_values(
        by=[*CONTEXT_COLUMNS, "predicted_probability"],
        ascending=[True, True, False],
        kind="mergesort",
    )
    ranked["_rank"] = ranked.groupby(CONTEXT_COLUMNS, dropna=False).cumcount() + 1

    positive_ranks = (
        ranked.loc[ranked[TARGET_COLUMN] == 1]
        .groupby(CONTEXT_COLUMNS, dropna=False)["_rank"]
        .min()
    )
    evaluated_contexts = int(len(positive_ranks))

    if evaluated_contexts == 0:
        return {
            "sampled_top1_accuracy": float("nan"),
            "sampled_top3_accuracy": float("nan"),
            "sampled_top5_accuracy": float("nan"),
            "evaluated_contexts": 0,
            "skipped_contexts_no_positive": skipped_no_positive,
            "contexts_multiple_positive": multiple_positive,
        }

    return {
        "sampled_top1_accuracy": float((positive_ranks <= 1).mean()),
        "sampled_top3_accuracy": float((positive_ranks <= 3).mean()),
        "sampled_top5_accuracy": float((positive_ranks <= 5).mean()),
        "evaluated_contexts": evaluated_contexts,
        "skipped_contexts_no_positive": skipped_no_positive,
        "contexts_multiple_positive": multiple_positive,
    }


def evaluate_split(model_name: str, model: Any, df: Any, X: Any, y: Any) -> tuple[dict[str, Any], Any]:
    y_prob = predict_proba_safely(model, X)
    metrics = {"model_name": model_name}
    metrics.update(compute_binary_metrics(y, y_prob))
    metrics.update(compute_sampled_topk_metrics(df, y_prob))
    return metrics, y_prob


def final_estimator(model: Any) -> Any:
    if hasattr(model, "named_steps") and "model" in model.named_steps:
        return model.named_steps["model"]
    return model


def extract_feature_importance(
    model: Any,
    model_name: str,
    feature_columns: Sequence[str],
) -> list[dict[str, Any]]:
    """Extract feature importance rows for models that expose it."""

    import numpy as np

    estimator = final_estimator(model)
    importances = None
    signed = None
    importance_type = ""

    try:
        if model_name == "logistic_regression" and hasattr(estimator, "coef_"):
            signed = np.asarray(estimator.coef_, dtype=float).reshape(-1)
            importances = np.abs(signed)
            importance_type = "abs_logistic_coefficient"
        elif hasattr(estimator, "feature_importances_"):
            importances = np.asarray(estimator.feature_importances_, dtype=float).reshape(-1)
            signed = importances
            importance_type = "feature_importances_"
        elif hasattr(estimator, "get_feature_importance"):
            importances = np.asarray(estimator.get_feature_importance(), dtype=float).reshape(-1)
            signed = importances
            importance_type = "feature_importances_"
    except Exception as exc:
        warnings.warn(f"{model_name}: could not extract feature importance: {exc}")
        return []

    if importances is None or len(importances) != len(feature_columns):
        warnings.warn(f"{model_name}: feature importance is unavailable.")
        return []

    rows = []
    for index, feature in enumerate(feature_columns):
        rows.append(
            {
                "model_name": model_name,
                "feature": feature,
                "importance": float(importances[index]),
                "signed_importance": float(signed[index]) if signed is not None else float(importances[index]),
                "importance_type": importance_type,
            }
        )
    return rows


def metric_desc_sort_value(value: Any) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return -math.inf
    return -math.inf if math.isnan(numeric) else numeric


def metric_asc_sort_value(value: Any) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return math.inf
    return math.inf if math.isnan(numeric) else numeric


def select_best_model(validation_results: Any) -> str:
    if validation_results.empty:
        raise ValueError("No validation results available for model selection.")

    sortable = validation_results.copy()
    sortable["_top1"] = sortable["sampled_top1_accuracy"].apply(metric_desc_sort_value)
    sortable["_roc_auc"] = sortable["roc_auc"].apply(metric_desc_sort_value)
    sortable["_average_precision"] = sortable["average_precision"].apply(metric_desc_sort_value)
    sortable["_log_loss"] = sortable["log_loss"].apply(metric_asc_sort_value)

    sortable = sortable.sort_values(
        by=["_top1", "_roc_auc", "_average_precision", "_log_loss"],
        ascending=[False, False, False, True],
        kind="mergesort",
    )
    return str(sortable.iloc[0]["model_name"])


def prefix_metrics(df: Any, prefix: str) -> Any:
    renamed = df.copy()
    renamed = renamed.rename(
        columns={column: f"{prefix}_{column}" for column in renamed.columns if column != "model_name"}
    )
    return renamed


def build_combined_results(validation_results: Any, test_results: Any) -> Any:
    combined = prefix_metrics(validation_results, "validation").merge(
        prefix_metrics(test_results, "test"),
        on="model_name",
        how="outer",
    )
    return combined


def json_clean(value: Any) -> Any:
    import numpy as np

    if isinstance(value, dict):
        return {str(key): json_clean(item) for key, item in value.items()}
    if isinstance(value, list):
        return [json_clean(item) for item in value]
    if isinstance(value, tuple):
        return [json_clean(item) for item in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        value = float(value)
    if isinstance(value, float) and math.isnan(value):
        return None
    return value


def build_best_model_summary(
    best_model_name: str,
    validation_results: Any,
    test_results: Any,
    feature_columns: Sequence[str],
    split_summaries: dict[str, dict[str, Any]],
    seed: int,
    input_dir: Path,
    output_dir: Path,
) -> dict[str, Any]:
    validation_row = validation_results.loc[
        validation_results["model_name"] == best_model_name
    ].iloc[0]
    test_row = test_results.loc[test_results["model_name"] == best_model_name].iloc[0]

    return {
        "model_name": best_model_name,
        "selection_metric": "validation_sampled_top1_accuracy",
        "validation_sampled_top1_accuracy": validation_row.get("sampled_top1_accuracy"),
        "validation_sampled_top3_accuracy": validation_row.get("sampled_top3_accuracy"),
        "validation_sampled_top5_accuracy": validation_row.get("sampled_top5_accuracy"),
        "validation_roc_auc": validation_row.get("roc_auc"),
        "validation_f1": validation_row.get("f1"),
        "validation_average_precision": validation_row.get("average_precision"),
        "validation_log_loss": validation_row.get("log_loss"),
        "test_sampled_top1_accuracy": test_row.get("sampled_top1_accuracy"),
        "test_sampled_top3_accuracy": test_row.get("sampled_top3_accuracy"),
        "test_sampled_top5_accuracy": test_row.get("sampled_top5_accuracy"),
        "test_roc_auc": test_row.get("roc_auc"),
        "test_f1": test_row.get("f1"),
        "test_average_precision": test_row.get("average_precision"),
        "test_log_loss": test_row.get("log_loss"),
        "feature_columns_used": ",".join(feature_columns),
        "train_rows": split_summaries["train"]["rows"],
        "validation_rows": split_summaries["validation"]["rows"],
        "test_rows": split_summaries["test"]["rows"],
        "seed": seed,
        "input_dir": str(input_dir),
        "output_dir": str(output_dir),
    }


def save_model(model: Any, path: Path) -> None:
    import joblib

    joblib.dump(model, path)


def save_prediction_file(df: Any, y_prob: Any, model_name: str, output_path: Path) -> None:
    output_columns = [column for column in PREDICTION_ID_COLUMNS if column in df.columns]
    missing = [column for column in PREDICTION_ID_COLUMNS if column not in df.columns]
    if missing:
        warnings.warn(f"{model_name}: prediction file missing ID columns: {missing}")

    predictions = df.loc[:, output_columns].copy()
    predictions["predicted_probability"] = y_prob
    predictions["model_name"] = model_name
    predictions.to_csv(output_path, index=False)


def save_outputs(
    *,
    output_dir: Path,
    validation_results: Any,
    test_results: Any,
    combined_results: Any,
    best_summary: dict[str, Any],
    feature_columns: Sequence[str],
    missing_default_features: Sequence[str],
    feature_importance_rows: list[dict[str, Any]],
    trained_model_rows: list[dict[str, Any]],
    skipped_model_rows: list[dict[str, Any]],
    training_run_summary: dict[str, Any],
) -> None:
    import pandas as pd

    validation_results.to_csv(output_dir / "model_comparison_validation.csv", index=False)
    test_results.to_csv(output_dir / "model_comparison_test.csv", index=False)
    combined_results.to_csv(output_dir / "model_comparison_combined.csv", index=False)

    pd.DataFrame([best_summary]).to_csv(output_dir / "best_model_summary.csv", index=False)
    with (output_dir / "best_model_summary.json").open("w", encoding="utf-8") as file_obj:
        json.dump(json_clean(best_summary), file_obj, indent=2)
        file_obj.write("\n")

    feature_column_payload = {
        "feature_columns": list(feature_columns),
        "missing_default_features": list(missing_default_features),
        "excluded_feature_columns": sorted(EXCLUDED_FEATURE_COLUMNS),
    }
    with (output_dir / "feature_columns.json").open("w", encoding="utf-8") as file_obj:
        json.dump(feature_column_payload, file_obj, indent=2)
        file_obj.write("\n")

    pd.DataFrame(feature_importance_rows, columns=FEATURE_IMPORTANCE_COLUMNS).to_csv(
        output_dir / "feature_importance.csv",
        index=False,
    )
    pd.DataFrame(trained_model_rows, columns=MODEL_TRAINED_COLUMNS).to_csv(
        output_dir / "models_trained.csv",
        index=False,
    )
    pd.DataFrame(skipped_model_rows, columns=MODEL_SKIPPED_COLUMNS).to_csv(
        output_dir / "models_skipped.csv",
        index=False,
    )
    pd.DataFrame([training_run_summary]).to_csv(
        output_dir / "training_run_summary.csv",
        index=False,
    )


def prepare_output_dir(output_dir: Path, overwrite: bool) -> tuple[Path, Path | None]:
    backup_dir = None
    generated_names = {
        "model_comparison_validation.csv",
        "model_comparison_test.csv",
        "model_comparison_combined.csv",
        "best_model_summary.csv",
        "best_model_summary.json",
        "feature_columns.json",
        "feature_importance.csv",
        "models_trained.csv",
        "models_skipped.csv",
        "training_run_summary.csv",
        "models",
        "predictions",
    }

    if output_dir.exists() and any(output_dir.iterdir()) and not overwrite:
        raise FileExistsError(
            f"Output directory exists and is not empty: {output_dir}. "
            "Use --overwrite to replace generated outputs."
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    if overwrite:
        for name in generated_names:
            target = output_dir / name
            if target.is_dir():
                shutil.rmtree(target)
            elif target.exists():
                target.unlink()

    models_dir = output_dir / "models"
    models_dir.mkdir(parents=True, exist_ok=True)
    return models_dir, backup_dir


def train_and_evaluate(args: argparse.Namespace) -> None:
    import pandas as pd

    config = load_config(args.config)
    settings = resolve_runtime_settings(args, config)
    input_dir: Path = settings["input_dir"]
    output_dir: Path = settings["output_dir"]
    seed: int = settings["seed"]
    requested_models = requested_models_from_args(args, config)

    print(f"Input directory: {input_dir}")
    print(f"Output directory: {output_dir}")
    print(f"Seed: {seed}")
    print(f"Requested models: {requested_models}")

    needed_columns = list(dict.fromkeys([*PREDICTION_ID_COLUMNS, *DEFAULT_FEATURE_COLUMNS]))
    split_frames = {
        split: read_pairwise_split(input_dir, split, args.input_format, needed_columns)
        for split in VALID_SPLITS
    }

    for split, df in split_frames.items():
        validate_pairwise_data(df, split)

    split_frames["train"] = sample_decision_contexts(
        split_frames["train"], args.max_train_contexts, seed
    )
    if args.max_train_contexts is None:
        split_frames["train"] = sample_rows(
            split_frames["train"], args.max_train_rows, seed, "train"
        )
    split_frames["validation"] = sample_decision_contexts(
        split_frames["validation"], args.max_validation_contexts, seed
    )
    split_frames["test"] = sample_decision_contexts(
        split_frames["test"], args.max_test_contexts, seed
    )

    split_summaries = {
        split: validate_pairwise_data(df, split) for split, df in split_frames.items()
    }

    train_features = get_feature_columns(split_frames["train"])
    common_features = [
        feature
        for feature in train_features
        if all(feature in split_frames[split].columns for split in VALID_SPLITS)
    ]
    missing_default_features = [
        feature
        for feature in DEFAULT_FEATURE_COLUMNS
        if feature not in common_features
    ]
    if missing_default_features:
        warnings.warn(
            "The following default features are unavailable in all splits and "
            f"will not be used: {missing_default_features}"
        )
    if not common_features:
        raise ValueError("No usable feature columns are present in all splits.")

    print(f"Feature columns used ({len(common_features)}): {common_features}")

    models_dir, _backup_dir = prepare_output_dir(output_dir, args.overwrite)
    predictions_dir = output_dir / "predictions"
    if args.save_predictions:
        predictions_dir.mkdir(parents=True, exist_ok=True)

    X_train, y_train = prepare_xy(split_frames["train"], common_features)
    X_validation, y_validation = prepare_xy(split_frames["validation"], common_features)
    X_test, y_test = prepare_xy(split_frames["test"], common_features)

    validation_results = []
    test_results = []
    trained_models = {}
    trained_model_rows = []
    skipped_model_rows = []
    feature_importance_rows = []
    validation_predictions = {}
    test_predictions = {}

    for model_name in requested_models:
        print(f"\nTraining model: {model_name}")
        try:
            model = train_model(model_name, X_train, y_train, seed, args.class_weight)
            validation_metrics, validation_prob = evaluate_split(
                model_name, model, split_frames["validation"], X_validation, y_validation
            )
            test_metrics, test_prob = evaluate_split(
                model_name, model, split_frames["test"], X_test, y_test
            )

            model_path = models_dir / f"{model_name}.joblib"
            save_model(model, model_path)

            validation_results.append(validation_metrics)
            test_results.append(test_metrics)
            trained_models[model_name] = model
            trained_model_rows.append(
                {"model_name": model_name, "model_path": str(model_path)}
            )
            feature_importance_rows.extend(
                extract_feature_importance(model, model_name, common_features)
            )
            validation_predictions[model_name] = validation_prob
            test_predictions[model_name] = test_prob

            print(
                f"{model_name}: validation top1="
                f"{validation_metrics['sampled_top1_accuracy']}, "
                f"test top1={test_metrics['sampled_top1_accuracy']}"
            )
        except Exception as exc:
            reason = f"{type(exc).__name__}: {exc}"
            print(f"Skipping {model_name}: {reason}")
            skipped_model_rows.append({"model_name": model_name, "reason": reason})

    validation_results_df = pd.DataFrame(validation_results)
    test_results_df = pd.DataFrame(test_results)
    skipped_models_df = pd.DataFrame(skipped_model_rows, columns=MODEL_SKIPPED_COLUMNS)

    skipped_models_df.to_csv(output_dir / "models_skipped.csv", index=False)

    if validation_results_df.empty or not trained_models:
        raise RuntimeError(
            "No requested models trained successfully. "
            f"See {output_dir / 'models_skipped.csv'} for details."
        )

    best_model_name = select_best_model(validation_results_df)
    best_model = trained_models[best_model_name]
    save_model(best_model, models_dir / "best_model.joblib")

    if args.save_predictions:
        for model_name in trained_models:
            save_prediction_file(
                split_frames["validation"],
                validation_predictions[model_name],
                model_name,
                predictions_dir / f"validation_predictions_{model_name}.csv",
            )
            save_prediction_file(
                split_frames["test"],
                test_predictions[model_name],
                model_name,
                predictions_dir / f"test_predictions_{model_name}.csv",
            )

    combined_results = build_combined_results(validation_results_df, test_results_df)
    best_summary = build_best_model_summary(
        best_model_name=best_model_name,
        validation_results=validation_results_df,
        test_results=test_results_df,
        feature_columns=common_features,
        split_summaries=split_summaries,
        seed=seed,
        input_dir=input_dir,
        output_dir=output_dir,
    )

    training_run_summary = {
        "run_timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "input_dir": str(input_dir),
        "output_dir": str(output_dir),
        "input_format": args.input_format,
        "seed": seed,
        "class_weight": args.class_weight,
        "models_requested": ",".join(requested_models),
        "models_trained": ",".join(trained_models.keys()),
        "models_skipped": ",".join(row["model_name"] for row in skipped_model_rows),
        "best_model_name": best_model_name,
        "feature_count": len(common_features),
        "feature_columns_used": ",".join(common_features),
        "max_train_contexts": args.max_train_contexts,
        "max_validation_contexts": args.max_validation_contexts,
        "max_test_contexts": args.max_test_contexts,
        "max_train_rows": args.max_train_rows,
        "save_predictions": bool(args.save_predictions),
        "train_rows": split_summaries["train"]["rows"],
        "validation_rows": split_summaries["validation"]["rows"],
        "test_rows": split_summaries["test"]["rows"],
        "train_decision_contexts": split_summaries["train"]["decision_contexts"],
        "validation_decision_contexts": split_summaries["validation"]["decision_contexts"],
        "test_decision_contexts": split_summaries["test"]["decision_contexts"],
    }

    save_outputs(
        output_dir=output_dir,
        validation_results=validation_results_df,
        test_results=test_results_df,
        combined_results=combined_results,
        best_summary=best_summary,
        feature_columns=common_features,
        missing_default_features=missing_default_features,
        feature_importance_rows=feature_importance_rows,
        trained_model_rows=trained_model_rows,
        skipped_model_rows=skipped_model_rows,
        training_run_summary=training_run_summary,
    )

    print("\nFull preference model training complete.")
    print(f"Models trained: {', '.join(trained_models.keys())}")
    if skipped_model_rows:
        print(
            "Models skipped: "
            f"{', '.join(row['model_name'] for row in skipped_model_rows)}"
        )
    else:
        print("Models skipped: None")
    print(f"Best model: {best_model_name}")
    print(f"Output directory: {output_dir}")


def main() -> int:
    args = parse_args()
    try:
        train_and_evaluate(args)
    except Exception as exc:
        print(f"ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
